
# MUST for Railway
server.port=${PORT:8080}
server.address=0.0.0.0

# Database (replace with Railway values)
spring.datasource.url= jdbc:mysql://:3306/railway
spring.datasource.username=root
spring.datasource.password=FLfDpAwxdVEssCDqTqFxYbuEjiRTjRTg
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

